/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAnnouncementsRouteImport } from './routes/app/announcements'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppGradesRouteImport } from './routes/app/grades'
import { Route as AppScheduleRouteImport } from './routes/app/schedule'
import { Route as AppSelfgovRouteImport } from './routes/app/selfgov'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppStudentsRouteImport } from './routes/app/students'
import { Route as AppTasksRouteImport } from './routes/app/tasks'
import { Route as AppTeachersRouteImport } from './routes/app/teachers'
import { Route as OnboardingLinkRouteImport } from './routes/onboarding/link'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding/role'
import { Route as OnboardingSchoolRouteImport } from './routes/onboarding/school'
import { Route as OnboardingSetupRouteImport } from './routes/onboarding/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSelfgovRoute = AppSelfgovRouteImport.update({
  id: '/selfgov',
  path: '/selfgov',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingLinkRoute = OnboardingLinkRouteImport.update({
  id: '/onboarding/link',
  path: '/onboarding/link',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSchoolRoute = OnboardingSchoolRouteImport.update({
  id: '/onboarding/school',
  path: '/onboarding/school',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSetupRoute = OnboardingSetupRouteImport.update({
  id: '/onboarding/setup',
  path: '/onboarding/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/chat': typeof AppChatRoute
  '/app/grades': typeof AppGradesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/selfgov': typeof AppSelfgovRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/teachers': typeof AppTeachersRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/chat': typeof AppChatRoute
  '/app/grades': typeof AppGradesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/selfgov': typeof AppSelfgovRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/teachers': typeof AppTeachersRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/student': typeof StudentRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/chat': typeof AppChatRoute
  '/app/grades': typeof AppGradesRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/selfgov': typeof AppSelfgovRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/teachers': typeof AppTeachersRoute
  '/onboarding/link': typeof OnboardingLinkRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/school': typeof OnboardingSchoolRoute
  '/onboarding/setup': typeof OnboardingSetupRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/student'
    | '/app/announcements'
    | '/app/chat'
    | '/app/grades'
    | '/app/schedule'
    | '/app/selfgov'
    | '/app/settings'
    | '/app/students'
    | '/app/tasks'
    | '/app/teachers'
    | '/onboarding/link'
    | '/onboarding/role'
    | '/onboarding/school'
    | '/onboarding/setup'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student'
    | '/app/announcements'
    | '/app/chat'
    | '/app/grades'
    | '/app/schedule'
    | '/app/selfgov'
    | '/app/settings'
    | '/app/students'
    | '/app/tasks'
    | '/app/teachers'
    | '/onboarding/link'
    | '/onboarding/role'
    | '/onboarding/school'
    | '/onboarding/setup'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/student'
    | '/app/announcements'
    | '/app/chat'
    | '/app/grades'
    | '/app/schedule'
    | '/app/selfgov'
    | '/app/settings'
    | '/app/students'
    | '/app/tasks'
    | '/app/teachers'
    | '/onboarding/link'
    | '/onboarding/role'
    | '/onboarding/school'
    | '/onboarding/setup'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRoute
  OnboardingLinkRoute: typeof OnboardingLinkRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSchoolRoute: typeof OnboardingSchoolRoute
  OnboardingSetupRoute: typeof OnboardingSetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/selfgov': {
      id: '/app/selfgov'
      path: '/selfgov'
      fullPath: '/app/selfgov'
      preLoaderRoute: typeof AppSelfgovRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teachers': {
      id: '/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/link': {
      id: '/onboarding/link'
      path: '/onboarding/link'
      fullPath: '/onboarding/link'
      preLoaderRoute: typeof OnboardingLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/school': {
      id: '/onboarding/school'
      path: '/onboarding/school'
      fullPath: '/onboarding/school'
      preLoaderRoute: typeof OnboardingSchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/setup': {
      id: '/onboarding/setup'
      path: '/onboarding/setup'
      fullPath: '/onboarding/setup'
      preLoaderRoute: typeof OnboardingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppChatRoute: typeof AppChatRoute
  AppGradesRoute: typeof AppGradesRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSelfgovRoute: typeof AppSelfgovRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppChatRoute: AppChatRoute,
  AppGradesRoute: AppGradesRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSelfgovRoute: AppSelfgovRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRoute,
  OnboardingLinkRoute: OnboardingLinkRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSchoolRoute: OnboardingSchoolRoute,
  OnboardingSetupRoute: OnboardingSetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
